// ===== 鏁呬簨妯″潡鍏ュ彛 =====
// 绾﹀畾锛氱ǔ瀹氭晠浜嬫ā鍧楁寜渚濊禆椤哄簭鐧昏鍦ㄨ繖閲岋紝index.html 鍙姞杞芥湰鏂囦欢銆?
// 杩欓噷鏄寮忔ā鍧楁竻鍗曪紝涓嶅啀浣跨敤鐗堟湰琛ヤ竵璇箟銆?

(function loadStoryModules() {
  const modules = [
    'src/story-modules/runtime-contract.js',
    'src/story-modules/consistency.js',
    'src/story-modules/evidence.js',
    'src/story-modules/narrative-depth.js',
    'src/story-modules/engine-ui-runtime-restore.js',
    'src/story-modules/ui-responsive.js',
    'src/story-modules/region-gates.js',
    'src/story-modules/fusheng-choice-polish.js',
    'src/story-modules/route-prereq-gates.js',
    'src/story-modules/xuehua-choice-polish.js',
    'src/story-modules/xuehua-203-evidence-polish.js',
    'src/story-modules/xuehua-source-gate.js',
    'src/story-modules/wang-note-prereq.js',
    'src/story-modules/investigation-guidance.js',
    'src/story-modules/home-route-polish.js',
    'src/story-modules/su-home-trust-gate.js',
    'src/story-modules/present-ui-polish.js',
    'src/story-modules/zhou-ending-polish.js',
    'src/story-modules/fusheng-progress-polish.js',
    'src/story-modules/player-perspective-polish.js',
    'src/story-modules/opening-intake-polish.js',
    'src/story-modules/guanghua-school-flow-polish.js',
    'src/story-modules/early-mist-perspective-polish.js',
    'src/story-modules/xuehua-203-route-unlock.js',
    'src/story-modules/guanghua-incomplete-closure-polish.js',
    'src/story-modules/guanghua-confront-choice-cleanup.js',
    'src/story-modules/location-hub-flow-polish.js',
    'src/story-modules/location-hub-detail-text-polish.js',
    'src/story-modules/present-flow-cleanup.js',
    'src/story-modules/zhou-jade-present-node-fix.js',
    'src/story-modules/deduction-flow-guidance.js',
    'src/story-modules/wrapup-priority-guidance.js',
    'src/story-modules/premature-conclusion-polish.js',
    'src/story-modules/early-ending-continuity-polish.js',
    'src/story-modules/deduction-retry-no-early-ending-polish.js',
    'src/story-modules/pressure-quality-ending-polish.js',
    'src/story-modules/narrative-clock-polish.js',
    'src/story-modules/true-ending-route-polish.js',
    'src/story-modules/sun-support-evidence-panel.js',
    'src/story-modules/sun-fast-support-polish.js',
    'src/story-modules/dock-hide-consequence-polish.js',
    'src/story-modules/dock-infiltration-depth-polish.js',
    'src/story-modules/dock-heat-system-polish.js',
    'src/story-modules/dock-fast-support-dual-balance-polish.js',
    'src/story-modules/dock-escape-choice-polish.js',
    'src/story-modules/dock-exit-hospital-tension-polish.js',
    'src/story-modules/fusheng-scene-evidence-panel.js',
    'src/story-modules/hidden-ending-gate-cleanup.js',
    'src/story-modules/hospital-flow-polish.js',
    'src/story-modules/hospital-pressure-witness-polish.js',
    'src/story-modules/hospital-truth-score-polish.js',
    'src/story-modules/lu-procedure-truth-polish.js',
    'src/story-modules/lu-evidence-panel.js',
    'src/story-modules/fusheng-key-gates-polish.js',
    'src/story-modules/hospital-triage-polish.js',
    'src/story-modules/solo-dock-hospital-polish.js',
    'src/story-modules/solo-entry-choice-label-polish.js',
    'src/story-modules/dock-hospital-continuity-polish.js',
    'src/story-modules/hospital-ending-impact-polish.js',
    'src/story-modules/dynamic-ending-polish.js',
    'src/story-modules/deadline-deprecation-polish.js',
    'src/story-modules/fusheng-decision-no-review.js',
    'src/story-modules/solo-reward-ending-polish.js',
    'src/story-modules/final-closure-flow-polish.js',
    'src/story-modules/legacy-quality-scope-polish.js',
    'src/story-modules/legacy-quality-text-polish.js',
    'src/story-modules/yufang-testimony-polish.js',
    'src/story-modules/hospital-pressure-witness-compat-fix.js',
    'src/story-modules/fu-private-offer-consequence-polish.js',
    'src/story-modules/darkroom-evidence-panel.js',
    'src/story-modules/conclusion-summary-polish.js',
    'src/story-modules/status-polish.js',
    'src/story-modules/ending-layout-polish.js',
    'src/story-modules/solo-heat-delay-outcomes.js',
    'src/story-modules/runtime-bugfixes.js',
    'src/story-modules/fusheng-entry-unblock-polish.js',
    'src/story-modules/wrapup-no-repeat-fusheng-entry-fix.js',
    'src/story-modules/causal-echo.js',
    'src/story-modules/yulan-echo-route-order-fix.js',
    'src/story-modules/su-home-early-keepsake-window.js',
    'src/story-modules/su-home-revisit-entry-fix.js',
    'src/story-modules/xuehua-blackman-timing-window.js',
    'src/story-modules/casebook-graph-polish.js',
    'src/story-modules/deduction-registry-final-fix.js',
    'src/story-modules/wrapup-dock-stage-final-fix.js',
    'src/story-modules/final-visible-text-tone-polish.js',
    'src/story-modules/dev-mode-panel.js',
    'src/story-modules/dev-diagnostic-export.js',
    'src/story-modules/guanghua-perspective-polish.js',
    'src/story-modules/player-name-gu.js'
  ];

  window.MLT_STORY_MODULES = modules.slice();

  for (const src of modules) {
    document.write(`<script src="${src}"><\/script>`);
  }
})();

